name: endemic_animals
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optioanl build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionname while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alterantively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/launcher_icon.png"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `aanlysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additioanl ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/launcher_icon.png
    - assets/loding.jpg
    - assets/1.jpg
    - assets/Af.png
    - assets/Ant.png
    - assets/As.png
    - assets/Au.png
    - assets/Eu.png
    - assets/Sa.png
    - assets/Na.png
    - assets/mo0.jpg
    - assets/mo1.webp
    - assets/mo2.jpg
    - assets/mo3.webp
    - assets/mo4.jpg
    - assets/mo5.jpg
    - assets/mo6.jpg
    - assets/mo7.jpg
    - assets/mo8.jpg
    - assets/mo9.jpg
    - assets/mo10.jpg
    - assets/Asia/a1.jpg
    - assets/Asia/as2.jpg
    - assets/Asia/as3.jpg
    - assets/Asia/as4.jpg
    - assets/Asia/as5.jpg
    - assets/Asia/as6.jpg
    - assets/Asia/as7.jpg
    - assets/Asia/as8.jpg
    - assets/Asia/as9.jpg
    - assets/Asia/as10.jpg
    - assets/Asia/as11.jpg
    - assets/Africa/af1.jpg
    - assets/Africa/af2.jpg
    - assets/Africa/af3.jpg
    - assets/Africa/af4.jpg
    - assets/Africa/af5.jpg
    - assets/Africa/af6.jpg
    - assets/Africa/af7.jpg
    - assets/Africa/af8.jpg
    - assets/Africa/af9.jpg
    - assets/Africa/af10.jpg
    - assets/Antac/an1.jpg
    - assets/Antac/an2.webp
    - assets/Antac/an3.jpg
    - assets/Antac/an4.jpg
    - assets/Antac/an5.jpg
    - assets/Antac/an6.jpg
    - assets/Austr/au1.jpg
    - assets/Austr/au2.jpg
    - assets/Austr/au3.jpg
    - assets/Austr/au4.jpg
    - assets/Austr/au5.jpg
    - assets/Austr/au6.jpg
    - assets/Austr/au7.jpg
    - assets/Austr/au8.png
    - assets/Austr/au9.jpg
    - assets/Austr/au10.jpg
    - assets/Euro/eu1.jpg
    - assets/Euro/eu2.jpg
    - assets/Euro/eu3.jpg
    - assets/Euro/eu4.jpg
    - assets/Euro/eu5.jpg
    - assets/Euro/eu6.jpg
    - assets/Euro/eu7.jpg
    - assets/Euro/eu8.jpg
    - assets/Noamr/nam1.jpg
    - assets/Noamr/nam2.jpg
    - assets/Noamr/nam3.jpg
    - assets/Noamr/nam4.jpg
    - assets/Noamr/nam5.jpg
    - assets/Noamr/nam6.jpg
    - assets/Noamr/nam7.jpg
    - assets/Noamr/nam8.jpg
    - assets/Noamr/nam9.jpg
    - assets/Noamr/nam10.jpg
    - assets/SoAmr/sam1.jpg
    - assets/SoAmr/sam2.jpg
    - assets/SoAmr/sam3.jpg
    - assets/SoAmr/sam4.jpg
    - assets/SoAmr/sam5.jpg
    - assets/SoAmr/sam6.jpg
    - assets/SoAmr/sam7.jpg
    - assets/SoAmr/sam8.jpg
    - assets/SoAmr/sam9.jpg
    - assets/SoAmr/sam10.jpg

     

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
